CREATE TABLE issue_tb (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    issue_key       VARCHAR(30)  NOT NULL,
    project_id      BIGINT       NOT NULL,
    project_key     VARCHAR(20)  NOT NULL,
    summary         VARCHAR(255) NOT NULL,
    description     TEXT,
    type            VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    priority        VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    sprint_id       BIGINT,
    assignee_id     BIGINT,
    reporter_id     BIGINT       NOT NULL,
    parent_issue_id BIGINT,
    story_points    INT,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    issue_order     BIGINT,
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at      DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_issue_key (issue_key),
    INDEX idx_issue_project (project_id),
    INDEX idx_issue_sprint (sprint_id),
    INDEX idx_issue_assignee (assignee_id),
    INDEX idx_issue_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
